
stages:
  - build

before_script:
    - pod install
    - gem install xcpretty -N
    - echo "ruby-2.4" > ~/.ruby-version

build_project:
  stage: build
  script:
    - set -o pipefail
    - xcodebuild build -workspace paymon.xcworkspace -scheme paymon -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  tags:
    - ios_10-3
    - osx_10_14_2
    - xcode_10-1