stages:
  - build

before_scripts:
     - pod install

build_project:
  stage: build
  script:
    - xcodebuild clean -workspace paymon.xcworkspace -scheme paymon | xcpretty
    - xcodebuild test -workspace paymon.xcworkspace -scheme paymon -destination 'platform=iOS Simulator,name=iPhone 8,OS=12.1' | xcpretty -s
  tags:
    - ios_10-3
    - osx_10_14_2
    - xcode_10-1