stages:
  - build

before_script:
    - pod install

build_project:
  stage: build
  script:
    - xcodebuild clean -workspace paymon.xcworkspace -scheme paymon | xcpretty
    - xcodebuild build -workspace paymon.xcworkspace -scheme paymon | xcpretty
  tags:
    - ios_10-3
    - osx_10_14_2
    - xcode_10-1