stages:
  - build

before_script:
    - pod install
    - gem install xcpretty -N

build_project:
  stage: build
  script:
    - set -o pipefail
    - xcodebuild build -workspace paymon.xcworkspace -scheme paymon -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO | xcpretty -c
  tags:
    - paymonteam-ios